[project]
name = "healthmate-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "gradio>=5.33.0",
    "httpx>=0.28.1",
    "langgraph>=0.4.8",
    "uvicorn>=0.34.3",
]
